# Generated by Django 4.2.1 on 2023-06-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbackk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(blank=True, max_length=120, null=True)),
                ('age', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
